// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'apps/builder/elementsbox/show/controller'], function(App) {
    return App.module('ElementsBoxApp', function(ElementsBoxApp, App, Backbone, Marionette, $, _) {
      var API;
      API = {
        show: function() {
          return new ElementsBoxApp.Show.Controller({
            region: App.elementsBoxRegion
          });
        },
        showFetchError: function(resp) {
          return new ElementsBoxApp.Show.ErrorController({
            region: App.elementsBoxRegion
          });
        }
      };
      ElementsBoxApp.on('start', function() {
        console.log("Elements module started");
        return API.show();
      });
      return App.vent.on("elementbox:collection:fetch:error", function(resp) {
        return API.showFetchError(resp);
      });
    });
  });

}).call(this);
