// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", 'backbone'], function(App, Backbone) {
    return App.module("Entities.Elements", function(Elements, App, Backbone, Marionette, $, _) {
      var API, _ref;
      Elements.ElementModel = (function(_super) {
        __extends(ElementModel, _super);

        function ElementModel() {
          _ref = ElementModel.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        ElementModel.prototype.url = function() {
          return "" + AJAXURL + "?action=element";
        };

        return ElementModel;

      })(Backbone.Model);
      API = {
        createElement: function(data) {
          var element;
          element = new Elements.ElementModel;
          element.save(data);
          return element;
        }
      };
      return App.reqres.setHandler("create:new:element", function(data) {
        return API.createElement(data);
      });
    });
  });

}).call(this);
