// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['app', 'text!apps/builder/site-builder/elements/contactform/templates/contactform.html'], function(App, contactformTpl) {
  return App.module('SiteBuilderApp.Element.ContactForm.Views', function(Views, App, Backbone, Marionette, $, _) {
    var _ref;
    return Views.ContactFormView = (function(_super) {
      __extends(ContactFormView, _super);

      function ContactFormView() {
        _ref = ContactFormView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ContactFormView.prototype.className = 'contactform';

      ContactFormView.prototype.template = contactformTpl;

      ContactFormView.prototype.onBeforeRender = function() {
        return this.className += " " + Marionette.getOption(this, 'className');
      };

      return ContactFormView;

    })(Marionette.ItemView);
  });
});
