define ['apps/builder/site-builder/elements/menu/controller'
		'apps/builder/site-builder/elements/row/controller'
		'apps/builder/site-builder/elements/logo/controller'
		'apps/builder/site-builder/elements/languageswitcher/controller'
		'apps/builder/site-builder/elements/text/controller'
		'apps/builder/site-builder/elements/title/controller'
		'apps/builder/site-builder/elements/image/controller'
		'apps/builder/site-builder/elements/imagewithtext/controller'
		'apps/builder/site-builder/elements/address/controller'
		'apps/builder/site-builder/elements/social/controller'
		'apps/builder/site-builder/elements/link/controller'
		'apps/builder/site-builder/elements/contactform/controller'
		'apps/builder/site-builder/elements/map/controller'
		'apps/builder/site-builder/elements/slider/controller' 
		'apps/builder/site-builder/elements/gallery/controller'
		'apps/builder/site-builder/elements/roomtitle/controller'
		'apps/builder/site-builder/elements/roomfacilities/controller'
		'apps/builder/site-builder/elements/roomdescription/controller'
		'apps/builder/site-builder/elements/roomtariff/controller'
		'apps/builder/site-builder/elements/roombooking/controller'
		'apps/builder/site-builder/elements/roomsummary/controller' ],->