// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['dashboard-app', 'apps/dashboard/show/controller'], function(App) {
    return App.module('DashboardApp', function(DashboardApp, App, Backbone, Marionette, $, _) {
      var API, _ref;
      DashboardApp.Router = (function(_super) {
        __extends(Router, _super);

        function Router() {
          _ref = Router.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Router.prototype.appRoutes = {
          'dashboard': 'show'
        };

        return Router;

      })(Marionette.AppRouter);
      API = {
        show: function() {
          var controller;
          controller = new DashboardApp.Show.Controller;
          return controller.showDashboard();
        }
      };
      return DashboardApp.on('start', function() {
        _.logAppMsg("DashboardApp Module started...");
        return new DashboardApp.Router({
          controller: API
        });
      });
    });
  });

}).call(this);
