// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['marionette', 'mustache', 'text!configs/marionette/templates/modal.html'], function(Marionette, Mustache, modalTpl) {
    var _ref;
    return Marionette.Region.Dialog = (function(_super) {
      __extends(Dialog, _super);

      function Dialog() {
        _ref = Dialog.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Dialog.prototype.template = modalTpl;

      Dialog.prototype.open = function(view) {
        var options, wrapper;
        options = view.dialogOptions ? view.dialogOptions : {};
        wrapper = Mustache.to_html(modalTpl, this._getOptions(options));
        this.$el.html(wrapper);
        return this.$el.find('.modal-body').append(view.el);
      };

      Dialog.prototype.onShow = function(view) {
        var _this = this;
        this.setupBindings(view);
        this.$el.modal();
        this.$el.modal('show');
        return this.$el.on('hidden.bs.modal', function() {
          return _this.clearDialog();
        });
      };

      Dialog.prototype.closeDialog = function() {
        return this.$el.modal('hide');
      };

      Dialog.prototype._getOptions = function(options) {
        return _.defaults(options, {
          modal_title: ''
        });
      };

      Dialog.prototype.setupBindings = function(view) {
        this.listenTo(view, 'dialog:close', this.closeDialog);
        return this.listenTo(view, 'dialog:resize', this.resizeDialog);
      };

      Dialog.prototype.clearDialog = function() {
        this.close();
        return this.$el.empty();
      };

      return Dialog;

    })(Marionette.Region);
  });

}).call(this);
