// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  var getRequireJSTasks, paths;
  require('time-grunt')(grunt);
  paths = {
    SPAPATH: 'wp-content/themes/impruwclientparent/app/dev'
  };
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    exec: {
      jitter: {
        cmd: 'jitter <%= pkg.SPAPATH %>/source/ <%= pkg.SPAPATH %>/js/ -b'
      }
    }
  });
  require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
  grunt.registerTask('default', []);
  grunt.registerTask('develop', ['exec:jitter']);
  grunt.registerTask('build', 'Build Production Js files', function() {
    var files, subTasks;
    files = grunt.file.expand("" + paths.SPAPATH + "/js/*-main.js");
    if (files.length === 0) {
      grunt.log.write("No files to optimize");
      return;
    }
    subTasks = getRequireJSTasks(files);
    grunt.config.set('requirejs', subTasks);
    return grunt.task.run("requirejs");
  });
  return getRequireJSTasks = function(files) {
    var subTasks;
    subTasks = {};
    files.map(function(file) {
      var config, configFilePath, fileName, name;
      fileName = file.replace("" + paths.SPAPATH + "/js/", "");
      configFilePath = "" + paths.SPAPATH + "/js/" + fileName;
      config = {
        baseUrl: "" + paths.SPAPATH + "/js/",
        mainConfigFile: configFilePath,
        name: "plugins/almond",
        include: ["" + fileName],
        out: "" + paths.SPAPATH + "/../production/" + fileName,
        findNestedDependencies: true,
        optimize: 'none'
      };
      name = fileName.replace(".js", "");
      subTasks[name] = {};
      return subTasks[name]["options"] = config;
    });
    return subTasks;
  };
};
