// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/media-manager/all-media/views'], function(App, AppController) {
    return App.module("MediaManager.AllMedia", function(AllMedia, App) {
      var _ref;
      this.startWithParent = false;
      AllMedia.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function() {
          var mediaCollection, view;
          mediaCollection = App.request("fetch:media", true);
          view = this._getView(mediaCollection);
          return this.show(view, {
            loading: true
          });
        };

        Controller.prototype._getView = function(mediaCollection) {
          return new AllMedia.Views.GridView({
            collection: mediaCollection
          });
        };

        return Controller;

      })(AppController);
      return AllMedia.on('start', function(options) {
        if (options == null) {
          options = {};
        }
        return new AllMedia.Controller({
          region: options.region
        });
      });
    });
  });

}).call(this);
