// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/my-profile/edit/views', 'entities/user'], function(App, AppController) {
    App.module('MyProfileApp.Edit', function(Edit, App, Backbone, Marionette, $, _) {
      var _ref;
      return Edit.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function() {
          return this.myProfile = App.request("get:my:profile");
        };

        Controller.prototype.showMyProfile = function() {
          var view;
          view = this.getMainView(this.myProfile);
          return this.show(view, {
            loading: true
          });
        };

        Controller.prototype.getMainView = function(model) {
          return new Edit.View.MainView({
            model: model
          });
        };

        return Controller;

      })(AppController);
    });
    return App.MyProfileApp.Edit.Controller;
  });

}).call(this);
