// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'tpl!apps/my-profile/edit/templates/mainview'], function(App, mainviewTpl) {
    App.module('MyProfileApp.Edit.View', function(View, App, Backbone, Marionette, $, _) {
      var _ref;
      return View.MainView = (function(_super) {
        __extends(MainView, _super);

        function MainView() {
          _ref = MainView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        MainView.prototype.template = mainviewTpl;

        MainView.prototype.events = {
          'click button[name="btn_saveusergeneral"]': 'submitUserGeneral'
        };

        MainView.prototype.onRender = function() {
          this.$el.find('input[type="checkbox"]').checkbox();
          this.$el.find('input[type="radio"]').radio();
          this.$el.find('select').selectpicker({
            style: 'btn-mini btn-default',
            menuStyle: 'dropdown'
          });
          return this.setupFormValidation();
        };

        MainView.prototype.setupFormValidation = function() {
          var forms;
          forms = this.$el.find('form');
          return $.each(forms, function(index, form) {
            $(form).validate();
          });
        };

        MainView.prototype.submitUserGeneral = function(evt) {
          var form;
          form = $(evt.target).closest('form');
          console.log(form);
          if ($(form).valid()) {
            return form.submit();
          }
        };

        return MainView;

      })(Marionette.ItemView);
    });
    return App.MyProfileApp.Edit.View;
  });

}).call(this);
