// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    return App.module('SiteBuilderApp.Element.Logo.Views', function(Views, App, Backbone, Marionette, $, _) {
      var _ref;
      return Views.LogoView = (function(_super) {
        __extends(LogoView, _super);

        function LogoView() {
          _ref = LogoView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        LogoView.prototype.className = 'logo';

        LogoView.prototype.template = '<a href="{{SITEURL}}"><img src="{{url}}" alt="{{title}}"/></a>';

        return LogoView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
