var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['app', 'backbone'], function(App, Backbone) {
  return App.module("Entities.Analytics", function(Analytics, App, Backbone, Marionette, $, _) {
    var API, analyticsCollection, date, eDate, sDate;
    Analytics.AnalyticsModel = (function(_super) {
      __extends(AnalyticsModel, _super);

      function AnalyticsModel() {
        return AnalyticsModel.__super__.constructor.apply(this, arguments);
      }

      AnalyticsModel.prototype.parse = function(resp) {};

      return AnalyticsModel;

    })(Backbone.Model);
    Analytics.AnalyticsCollection = (function(_super) {
      __extends(AnalyticsCollection, _super);

      function AnalyticsCollection() {
        return AnalyticsCollection.__super__.constructor.apply(this, arguments);
      }

      AnalyticsCollection.prototype.model = Analytics.AnalyticsModel;

      AnalyticsCollection.prototype.comparator = function(model) {
        return -model.get('date');
      };

      AnalyticsCollection.prototype.url = function() {
        return "" + AJAXURL + "?action=get_analytics_data";
      };

      return AnalyticsCollection;

    })(Backbone.Collection);
    date = new Date();
    eDate = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
    sDate = eDate - (180 * 86400000);
    analyticsCollection = new Analytics.AnalyticsCollection;
    analyticsCollection.set([
      {
        "date": 1.3807584e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3808448e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3809312e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3810176e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.381104e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3811904e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3812768e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3813632e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3814496e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.381536e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3816224e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3817088e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3817952e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3818816e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.381968e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3820544e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3821408e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3822272e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3823136e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3824e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3824864e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3825728e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3826592e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3827456e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.382832e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3829184e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3830048e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3830912e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3831776e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.383264e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3833504e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3834368e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3835232e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3836096e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.383696e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3837824e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3838688e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3839552e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3840416e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.384128e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3842144e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3843008e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3843872e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3844736e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.38456e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3846464e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3847328e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3848192e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3849056e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.384992e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3850784e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3851648e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3852512e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3853376e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.385424e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3855104e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3855968e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3856832e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3857696e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.385856e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3859424e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3860288e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3861152e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3862016e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.386288e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3863744e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3864608e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3865472e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3866336e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.38672e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3868064e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3868928e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3869792e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3870656e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.387152e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3872384e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3873248e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3874112e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3874976e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.387584e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3876704e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3877568e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3878432e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3879296e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.388016e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3881024e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3881888e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3882752e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3883616e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.388448e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3885344e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3886208e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3887072e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3887936e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.38888e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3889664e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3890528e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3891392e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3892256e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.389312e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3893984e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3894848e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3895712e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3896576e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.389744e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3898304e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3899168e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3900032e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3900896e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.390176e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3902624e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3903488e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3904352e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3905216e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.390608e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3906944e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3907808e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3908672e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3909536e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.39104e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3911264e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3912128e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3912992e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3913856e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.391472e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3915584e+12,
        "ga:visits": 6,
        "ga:newVisits": 6,
        "ga:visitBounceRate": 33.3333333333,
        "ga:avgTimeOnSite": 262.666666667,
        "ga:uniquePageviews": 17,
        "ga:pageviews": 19,
        "ga:pageviewsPerVisit": 3.16666666667
      }, {
        "date": 1.3916448e+12,
        "ga:visits": 26,
        "ga:newVisits": 22,
        "ga:visitBounceRate": 19.2307692308,
        "ga:avgTimeOnSite": 376.923076923,
        "ga:uniquePageviews": 79,
        "ga:pageviews": 116,
        "ga:pageviewsPerVisit": 4.46153846154
      }, {
        "date": 1.3917312e+12,
        "ga:visits": 38,
        "ga:newVisits": 33,
        "ga:visitBounceRate": 21.0526315789,
        "ga:avgTimeOnSite": 466.5,
        "ga:uniquePageviews": 156,
        "ga:pageviews": 223,
        "ga:pageviewsPerVisit": 5.86842105263
      }, {
        "date": 1.3918176e+12,
        "ga:visits": 14,
        "ga:newVisits": 12,
        "ga:visitBounceRate": 21.4285714286,
        "ga:avgTimeOnSite": 395.214285714,
        "ga:uniquePageviews": 55,
        "ga:pageviews": 77,
        "ga:pageviewsPerVisit": 5.5
      }, {
        "date": 1.391904e+12,
        "ga:visits": 12,
        "ga:newVisits": 11,
        "ga:visitBounceRate": 8.33333333333,
        "ga:avgTimeOnSite": 270.916666667,
        "ga:uniquePageviews": 53,
        "ga:pageviews": 60,
        "ga:pageviewsPerVisit": 5
      }, {
        "date": 1.3919904e+12,
        "ga:visits": 33,
        "ga:newVisits": 23,
        "ga:visitBounceRate": 39.3939393939,
        "ga:avgTimeOnSite": 501.484848485,
        "ga:uniquePageviews": 134,
        "ga:pageviews": 184,
        "ga:pageviewsPerVisit": 5.57575757576
      }, {
        "date": 1.3920768e+12,
        "ga:visits": 30,
        "ga:newVisits": 24,
        "ga:visitBounceRate": 20,
        "ga:avgTimeOnSite": 214.4,
        "ga:uniquePageviews": 121,
        "ga:pageviews": 145,
        "ga:pageviewsPerVisit": 4.83333333333
      }, {
        "date": 1.3921632e+12,
        "ga:visits": 13,
        "ga:newVisits": 8,
        "ga:visitBounceRate": 61.5384615385,
        "ga:avgTimeOnSite": 366.153846154,
        "ga:uniquePageviews": 43,
        "ga:pageviews": 55,
        "ga:pageviewsPerVisit": 4.23076923077
      }, {
        "date": 1.3922496e+12,
        "ga:visits": 26,
        "ga:newVisits": 22,
        "ga:visitBounceRate": 26.9230769231,
        "ga:avgTimeOnSite": 247.961538462,
        "ga:uniquePageviews": 98,
        "ga:pageviews": 125,
        "ga:pageviewsPerVisit": 4.80769230769
      }, {
        "date": 1.392336e+12,
        "ga:visits": 26,
        "ga:newVisits": 13,
        "ga:visitBounceRate": 11.5384615385,
        "ga:avgTimeOnSite": 327.615384615,
        "ga:uniquePageviews": 105,
        "ga:pageviews": 149,
        "ga:pageviewsPerVisit": 5.73076923077
      }, {
        "date": 1.3924224e+12,
        "ga:visits": 14,
        "ga:newVisits": 12,
        "ga:visitBounceRate": 35.7142857143,
        "ga:avgTimeOnSite": 140,
        "ga:uniquePageviews": 48,
        "ga:pageviews": 56,
        "ga:pageviewsPerVisit": 4
      }, {
        "date": 1.3925088e+12,
        "ga:visits": 11,
        "ga:newVisits": 8,
        "ga:visitBounceRate": 36.3636363636,
        "ga:avgTimeOnSite": 253.636363636,
        "ga:uniquePageviews": 43,
        "ga:pageviews": 49,
        "ga:pageviewsPerVisit": 4.45454545455
      }, {
        "date": 1.3925952e+12,
        "ga:visits": 31,
        "ga:newVisits": 25,
        "ga:visitBounceRate": 22.5806451613,
        "ga:avgTimeOnSite": 224.483870968,
        "ga:uniquePageviews": 109,
        "ga:pageviews": 137,
        "ga:pageviewsPerVisit": 4.41935483871
      }, {
        "date": 1.3926816e+12,
        "ga:visits": 27,
        "ga:newVisits": 22,
        "ga:visitBounceRate": 22.2222222222,
        "ga:avgTimeOnSite": 392.592592593,
        "ga:uniquePageviews": 90,
        "ga:pageviews": 112,
        "ga:pageviewsPerVisit": 4.14814814815
      }, {
        "date": 1.392768e+12,
        "ga:visits": 22,
        "ga:newVisits": 16,
        "ga:visitBounceRate": 18.1818181818,
        "ga:avgTimeOnSite": 412.318181818,
        "ga:uniquePageviews": 92,
        "ga:pageviews": 134,
        "ga:pageviewsPerVisit": 6.09090909091
      }, {
        "date": 1.3928544e+12,
        "ga:visits": 14,
        "ga:newVisits": 13,
        "ga:visitBounceRate": 14.2857142857,
        "ga:avgTimeOnSite": 406.642857143,
        "ga:uniquePageviews": 75,
        "ga:pageviews": 103,
        "ga:pageviewsPerVisit": 7.35714285714
      }, {
        "date": 1.3929408e+12,
        "ga:visits": 22,
        "ga:newVisits": 20,
        "ga:visitBounceRate": 40.9090909091,
        "ga:avgTimeOnSite": 282,
        "ga:uniquePageviews": 64,
        "ga:pageviews": 73,
        "ga:pageviewsPerVisit": 3.31818181818
      }, {
        "date": 1.3930272e+12,
        "ga:visits": 13,
        "ga:newVisits": 12,
        "ga:visitBounceRate": 23.0769230769,
        "ga:avgTimeOnSite": 461.153846154,
        "ga:uniquePageviews": 34,
        "ga:pageviews": 42,
        "ga:pageviewsPerVisit": 3.23076923077
      }, {
        "date": 1.3931136e+12,
        "ga:visits": 18,
        "ga:newVisits": 11,
        "ga:visitBounceRate": 38.8888888889,
        "ga:avgTimeOnSite": 311,
        "ga:uniquePageviews": 43,
        "ga:pageviews": 46,
        "ga:pageviewsPerVisit": 2.55555555556
      }, {
        "date": 1.3932e+12,
        "ga:visits": 23,
        "ga:newVisits": 15,
        "ga:visitBounceRate": 43.4782608696,
        "ga:avgTimeOnSite": 395.565217391,
        "ga:uniquePageviews": 54,
        "ga:pageviews": 73,
        "ga:pageviewsPerVisit": 3.17391304348
      }, {
        "date": 1.3932864e+12,
        "ga:visits": 20,
        "ga:newVisits": 13,
        "ga:visitBounceRate": 40,
        "ga:avgTimeOnSite": 249.6,
        "ga:uniquePageviews": 46,
        "ga:pageviews": 51,
        "ga:pageviewsPerVisit": 2.55
      }, {
        "date": 1.3933728e+12,
        "ga:visits": 25,
        "ga:newVisits": 14,
        "ga:visitBounceRate": 44,
        "ga:avgTimeOnSite": 354.28,
        "ga:uniquePageviews": 62,
        "ga:pageviews": 101,
        "ga:pageviewsPerVisit": 4.04
      }, {
        "date": 1.3934592e+12,
        "ga:visits": 16,
        "ga:newVisits": 11,
        "ga:visitBounceRate": 37.5,
        "ga:avgTimeOnSite": 235.125,
        "ga:uniquePageviews": 43,
        "ga:pageviews": 52,
        "ga:pageviewsPerVisit": 3.25
      }, {
        "date": 1.3935456e+12,
        "ga:visits": 10,
        "ga:newVisits": 6,
        "ga:visitBounceRate": 30,
        "ga:avgTimeOnSite": 75.9,
        "ga:uniquePageviews": 29,
        "ga:pageviews": 37,
        "ga:pageviewsPerVisit": 3.7
      }, {
        "date": 1.393632e+12,
        "ga:visits": 13,
        "ga:newVisits": 10,
        "ga:visitBounceRate": 23.0769230769,
        "ga:avgTimeOnSite": 336,
        "ga:uniquePageviews": 75,
        "ga:pageviews": 112,
        "ga:pageviewsPerVisit": 8.61538461538
      }, {
        "date": 1.3937184e+12,
        "ga:visits": 7,
        "ga:newVisits": 3,
        "ga:visitBounceRate": 14.2857142857,
        "ga:avgTimeOnSite": 597.428571429,
        "ga:uniquePageviews": 19,
        "ga:pageviews": 41,
        "ga:pageviewsPerVisit": 5.85714285714
      }, {
        "date": 1.3938048e+12,
        "ga:visits": 27,
        "ga:newVisits": 17,
        "ga:visitBounceRate": 40.7407407407,
        "ga:avgTimeOnSite": 62.8518518519,
        "ga:uniquePageviews": 66,
        "ga:pageviews": 82,
        "ga:pageviewsPerVisit": 3.03703703704
      }, {
        "date": 1.3938912e+12,
        "ga:visits": 16,
        "ga:newVisits": 9,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 299.25,
        "ga:uniquePageviews": 68,
        "ga:pageviews": 92,
        "ga:pageviewsPerVisit": 5.75
      }, {
        "date": 1.3939776e+12,
        "ga:visits": 26,
        "ga:newVisits": 16,
        "ga:visitBounceRate": 34.6153846154,
        "ga:avgTimeOnSite": 231.615384615,
        "ga:uniquePageviews": 90,
        "ga:pageviews": 131,
        "ga:pageviewsPerVisit": 5.03846153846
      }, {
        "date": 1.394064e+12,
        "ga:visits": 5,
        "ga:newVisits": 4,
        "ga:visitBounceRate": 20,
        "ga:avgTimeOnSite": 131,
        "ga:uniquePageviews": 15,
        "ga:pageviews": 16,
        "ga:pageviewsPerVisit": 3.2
      }, {
        "date": 1.3941504e+12,
        "ga:visits": 20,
        "ga:newVisits": 14,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 381.7,
        "ga:uniquePageviews": 95,
        "ga:pageviews": 138,
        "ga:pageviewsPerVisit": 6.9
      }, {
        "date": 1.3942368e+12,
        "ga:visits": 6,
        "ga:newVisits": 4,
        "ga:visitBounceRate": 50,
        "ga:avgTimeOnSite": 83,
        "ga:uniquePageviews": 11,
        "ga:pageviews": 11,
        "ga:pageviewsPerVisit": 1.83333333333
      }, {
        "date": 1.3943232e+12,
        "ga:visits": 1,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 100,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 1,
        "ga:pageviews": 1,
        "ga:pageviewsPerVisit": 1
      }, {
        "date": 1.3944096e+12,
        "ga:visits": 21,
        "ga:newVisits": 10,
        "ga:visitBounceRate": 23.8095238095,
        "ga:avgTimeOnSite": 292.904761905,
        "ga:uniquePageviews": 65,
        "ga:pageviews": 89,
        "ga:pageviewsPerVisit": 4.2380952381
      }, {
        "date": 1.394496e+12,
        "ga:visits": 24,
        "ga:newVisits": 15,
        "ga:visitBounceRate": 33.3333333333,
        "ga:avgTimeOnSite": 343.875,
        "ga:uniquePageviews": 80,
        "ga:pageviews": 118,
        "ga:pageviewsPerVisit": 4.91666666667
      }, {
        "date": 1.3945824e+12,
        "ga:visits": 29,
        "ga:newVisits": 19,
        "ga:visitBounceRate": 34.4827586207,
        "ga:avgTimeOnSite": 212.655172414,
        "ga:uniquePageviews": 89,
        "ga:pageviews": 117,
        "ga:pageviewsPerVisit": 4.03448275862
      }, {
        "date": 1.3946688e+12,
        "ga:visits": 8,
        "ga:newVisits": 4,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 247.875,
        "ga:uniquePageviews": 22,
        "ga:pageviews": 30,
        "ga:pageviewsPerVisit": 3.75
      }, {
        "date": 1.3947552e+12,
        "ga:visits": 19,
        "ga:newVisits": 13,
        "ga:visitBounceRate": 42.1052631579,
        "ga:avgTimeOnSite": 180.842105263,
        "ga:uniquePageviews": 51,
        "ga:pageviews": 78,
        "ga:pageviewsPerVisit": 4.10526315789
      }, {
        "date": 1.3948416e+12,
        "ga:visits": 6,
        "ga:newVisits": 2,
        "ga:visitBounceRate": 50,
        "ga:avgTimeOnSite": 66,
        "ga:uniquePageviews": 10,
        "ga:pageviews": 12,
        "ga:pageviewsPerVisit": 2
      }, {
        "date": 1.394928e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3950144e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3951008e+12,
        "ga:visits": 23,
        "ga:newVisits": 18,
        "ga:visitBounceRate": 17.3913043478,
        "ga:avgTimeOnSite": 281.130434783,
        "ga:uniquePageviews": 79,
        "ga:pageviews": 115,
        "ga:pageviewsPerVisit": 5
      }, {
        "date": 1.3951872e+12,
        "ga:visits": 1,
        "ga:newVisits": 1,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 103,
        "ga:uniquePageviews": 6,
        "ga:pageviews": 7,
        "ga:pageviewsPerVisit": 7
      }, {
        "date": 1.3952736e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.39536e+12,
        "ga:visits": 32,
        "ga:newVisits": 19,
        "ga:visitBounceRate": 28.125,
        "ga:avgTimeOnSite": 319.9375,
        "ga:uniquePageviews": 129,
        "ga:pageviews": 173,
        "ga:pageviewsPerVisit": 5.40625
      }, {
        "date": 1.3954464e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3955328e+12,
        "ga:visits": 16,
        "ga:newVisits": 9,
        "ga:visitBounceRate": 43.75,
        "ga:avgTimeOnSite": 195.3125,
        "ga:uniquePageviews": 60,
        "ga:pageviews": 97,
        "ga:pageviewsPerVisit": 6.0625
      }, {
        "date": 1.3956192e+12,
        "ga:visits": 35,
        "ga:newVisits": 24,
        "ga:visitBounceRate": 34.2857142857,
        "ga:avgTimeOnSite": 295.228571429,
        "ga:uniquePageviews": 124,
        "ga:pageviews": 169,
        "ga:pageviewsPerVisit": 4.82857142857
      }, {
        "date": 1.3957056e+12,
        "ga:visits": 16,
        "ga:newVisits": 14,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 660.5,
        "ga:uniquePageviews": 80,
        "ga:pageviews": 151,
        "ga:pageviewsPerVisit": 9.4375
      }, {
        "date": 1.395792e+12,
        "ga:visits": 23,
        "ga:newVisits": 17,
        "ga:visitBounceRate": 8.69565217391,
        "ga:avgTimeOnSite": 316.304347826,
        "ga:uniquePageviews": 95,
        "ga:pageviews": 144,
        "ga:pageviewsPerVisit": 6.26086956522
      }, {
        "date": 1.3958784e+12,
        "ga:visits": 20,
        "ga:newVisits": 18,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 179.1,
        "ga:uniquePageviews": 66,
        "ga:pageviews": 74,
        "ga:pageviewsPerVisit": 3.7
      }, {
        "date": 1.3959648e+12,
        "ga:visits": 22,
        "ga:newVisits": 18,
        "ga:visitBounceRate": 18.1818181818,
        "ga:avgTimeOnSite": 182.772727273,
        "ga:uniquePageviews": 81,
        "ga:pageviews": 109,
        "ga:pageviewsPerVisit": 4.95454545455
      }, {
        "date": 1.3960512e+12,
        "ga:visits": 0,
        "ga:newVisits": 0,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 0,
        "ga:pageviews": 0,
        "ga:pageviewsPerVisit": 0
      }, {
        "date": 1.3961376e+12,
        "ga:visits": 1,
        "ga:newVisits": 1,
        "ga:visitBounceRate": 100,
        "ga:avgTimeOnSite": 0,
        "ga:uniquePageviews": 1,
        "ga:pageviews": 1,
        "ga:pageviewsPerVisit": 1
      }, {
        "date": 1.396224e+12,
        "ga:visits": 12,
        "ga:newVisits": 8,
        "ga:visitBounceRate": 25,
        "ga:avgTimeOnSite": 117.166666667,
        "ga:uniquePageviews": 45,
        "ga:pageviews": 53,
        "ga:pageviewsPerVisit": 4.41666666667
      }, {
        "date": 1.3963104e+12,
        "ga:visits": 3,
        "ga:newVisits": 3,
        "ga:visitBounceRate": 0,
        "ga:avgTimeOnSite": 247.666666667,
        "ga:uniquePageviews": 19,
        "ga:pageviews": 40,
        "ga:pageviewsPerVisit": 13.3333333333
      }
    ]);
    API = {
      getAnalyticsData: function(startDate, endDate) {
        var collection, models;
        collection = new Analytics.AnalyticsCollection;
        models = analyticsCollection.filter(function(model) {
          date = model.get('date');
          return date >= startDate && date <= endDate;
        });
        collection.add(models);
        return collection;
      }
    };
    App.reqres.setHandler("get:weekly:data", function() {
      var endDate, startDate;
      date = new Date();
      endDate = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
      startDate = endDate - (7 * 86400000);
      return API.getAnalyticsData(startDate, endDate);
    });
    return App.reqres.setHandler("get:site:analytics:data", function(startDate, endDate) {
      return API.getAnalyticsData(startDate, endDate);
    });
  });
});
