// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", 'backbone'], function(App, Backbone) {
    var API, LeftNavItems, _ref;
    LeftNavItems = (function(_super) {
      __extends(LeftNavItems, _super);

      function LeftNavItems() {
        _ref = LeftNavItems.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return LeftNavItems;

    })(Backbone.Collection);
    API = {
      getLeftNavEntities: function(action, param) {
        var menuItems;
        if (param == null) {
          param = {};
        }
        menuItems = new LeftNavItems;
        menuItems.url = AJAXURL + '?action=get-menu-items';
        menuItems.fetch({
          reset: true,
          data: param
        });
        return menuItems;
      }
    };
    return App.reqres.setHandler("leftnav:entities", function() {
      return API.getLeftNavEntities();
    });
  });

}).call(this);
