// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", 'backbone'], function(App, Backbone) {
    return App.module("Entities.Media", function(Media, App, Backbone, Marionette, $, _) {
      var API, _ref, _ref1;
      Media.MediaModel = (function(_super) {
        __extends(MediaModel, _super);

        function MediaModel() {
          _ref = MediaModel.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        MediaModel.prototype.idAttribute = 'ID';

        MediaModel.prototype.parse = function(resp) {
          if (resp.code === 'OK') {
            return resp.data;
          }
          return resp;
        };

        return MediaModel;

      })(Backbone.AssociatedModel);
      Media.MediaCollection = (function(_super) {
        __extends(MediaCollection, _super);

        function MediaCollection() {
          _ref1 = MediaCollection.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        MediaCollection.prototype.model = Media.MediaModel;

        MediaCollection.prototype.url = function(models) {
          var ids, media, _i, _len;
          if (models == null) {
            models = [];
          }
          if (models.length === 0) {
            return "" + AJAXURL + "?action=media";
          } else {
            ids = [];
            for (_i = 0, _len = models.length; _i < _len; _i++) {
              media = models[_i];
              ids.push(media.get('ID'));
            }
            ids = ids.join();
            return "" + AJAXURL + "?action=media&ids=" + ids;
          }
        };

        return MediaCollection;

      })(Backbone.Collection);
      API = {
        getMedia: function(param) {
          var mediaCollection;
          if (param == null) {
            param = {};
          }
          mediaCollection = App.request("get:collection", 'mediacollection');
          if (!mediaCollection) {
            mediaCollection = new Media.MediaCollection;
          }
          if (!mediaCollection.fetched()) {
            media.fetch();
          }
          return media;
        },
        createStoreCollection: function() {
          var mediaCollection;
          mediaCollection = new Media.MediaCollection;
          return App.request("set:collection", 'mediacollection', mediaCollection);
        },
        getImageById: function(mediaId) {
          var media, mediaCollection;
          mediaCollection = App.request("get:collection", 'mediacollection');
          media = mediaCollection.get(parseInt(mediaId));
          if (_.isUndefined(media)) {
            media = new Media.MediaModel({
              ID: mediaId
            });
            media.url = "" + AJAXURL + "?action=get-media&ID=" + mediaId;
            mediaCollection.add(media);
            media.fetch();
          }
          return media;
        }
      };
      App.commands.setHandler("create:media:store", function() {
        return API.createStoreCollection();
      });
      App.reqres.setHandler("get:media:entities", function() {
        return API.getMedia();
      });
      return App.reqres.setHandler("get:media:by:id", function(mediaId) {
        return API.getImageById(mediaId);
      });
    });
  });

}).call(this);
