// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", 'backbone'], function(App, Backbone) {
    App.module("Entities.Menus", function(Menus, App, Backbone, Marionette, $, _) {
      var API, _ref, _ref1;
      Menus.MenuModel = (function(_super) {
        __extends(MenuModel, _super);

        function MenuModel() {
          _ref = MenuModel.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        return MenuModel;

      })(Backbone.Model);
      Menus.MenuCollection = (function(_super) {
        __extends(MenuCollection, _super);

        function MenuCollection() {
          _ref1 = MenuCollection.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        return MenuCollection;

      })(Backbone.Collection);
      API = {
        getMenus: function(param) {
          var menus;
          if (param == null) {
            param = {};
          }
          menus = new Menus.MenuCollection;
          menus.url = AJAXURL + '?action=get-menus';
          menus.fetch({
            reset: true,
            data: param
          });
          return menus;
        }
      };
      return App.reqres.setHandler("get:site:menus", function() {
        return API.getMenus();
      });
    });
    return App.Entities.Menus;
  });

}).call(this);
