// Generated by CoffeeScript 1.6.3
(function() {
  define(['app'], function(App) {
    return App.module("OfflineStore", function(OfflineStore, App) {
      var API;
      API = {
        getCollection: function(type) {
          var _ref;
          return (_ref = OfflineStore[type]) != null ? _ref : false;
        },
        getCollectionModel: function(collectionType, modelId) {
          var model;
          model = OfflineStore[collectionType].get(modelId);
          if (_.isUndefined(model)) {
            return false;
          }
        },
        setCollection: function(type, collection) {
          return OfflineStore[type] = collection;
        }
      };
      App.reqres.setHandler("get:collection", function(type) {
        return API.getCollection(type);
      });
      App.reqres.setHandler("set:collection", function(type, collection) {
        return API.setCollection(type, collection);
      });
      return App.reqres.setHandler("get:collection:model", function(collectionType, modelId) {
        return API.getCollectionModel(collectionType, modelId);
      });
    });
  });

}).call(this);
