// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", 'backbone'], function(App, Backbone) {
    return App.module("Entities.Site", function(Site, App, Backbone, Marionette, $, _) {
      var API, SiteModel, SiteSocialItem, SiteSocialItemsCollection, _ref, _ref1, _ref2;
      SiteModel = (function(_super) {
        __extends(SiteModel, _super);

        function SiteModel() {
          _ref = SiteModel.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        return SiteModel;

      })(Backbone.Model);
      SiteSocialItem = (function(_super) {
        __extends(SiteSocialItem, _super);

        function SiteSocialItem() {
          _ref1 = SiteSocialItem.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        SiteSocialItem.prototype.idAttribute = 'socialname';

        return SiteSocialItem;

      })(Backbone.Model);
      SiteSocialItemsCollection = (function(_super) {
        __extends(SiteSocialItemsCollection, _super);

        function SiteSocialItemsCollection() {
          _ref2 = SiteSocialItemsCollection.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        SiteSocialItemsCollection.prototype.model = SiteSocialItem;

        SiteSocialItemsCollection.prototype.url = function() {
          return "" + AJAXURL + "?action=get-site-socials";
        };

        SiteSocialItemsCollection.prototype.parse = function(r) {
          if (r.code === 'OK') {
            return r.data;
          }
          return r;
        };

        return SiteSocialItemsCollection;

      })(Backbone.Collection);
      API = {
        getSiteProfile: function() {
          var site;
          site = new SiteModel;
          site.url = AJAXURL + '?action=get-site-profile';
          site.fetch();
          return site;
        },
        getSiteSocial: function() {
          var socialCollection;
          socialCollection = App.request("get:collection", 'socialcollection');
          if (!socialCollection) {
            socialCollection = new SiteSocialItemsCollection;
          }
          if (socialCollection.length === 0) {
            socialCollection.fetch();
          }
          return socialCollection;
        },
        createSocialStoreCollection: function() {
          var socialCollection;
          socialCollection = new SiteSocialItemsCollection;
          return App.request("set:collection", 'socialcollection', socialCollection);
        }
      };
      App.reqres.setHandler("get:site:profile", function() {
        return API.getSiteProfile();
      });
      App.reqres.setHandler("get:site:social", function() {
        return API.getSiteSocial();
      });
      return App.commands.setHandler("create:social:store", function() {
        return API.createSocialStoreCollection();
      });
    });
  });

}).call(this);
