// Generated by CoffeeScript 1.6.3
(function() {
  define(['dashboard-app'], function(app) {
    return app.module('Room', function(Room, App, Backbone, Marionette, $, _) {
      this.startWithParent = false;
      return Room.on({
        'start': function() {
          return _.logAppMsg("Room Module started...");
        }
      });
    });
  });

}).call(this);
