// Generated by CoffeeScript 1.7.1
define(['app'], function(App) {
  return describe("Application object", function() {
    it("must have a application object", function() {
      return expect(App).toBeDefined();
    });
    it("must have a root route", function() {
      return expect(App.rootRoute).toBeDefined();
    });
    it("must have 3 regions", function() {
      return expect(App.leftRegion).toBeDefined();
    });
    it("must have a default:region handler", function() {
      return expect(App.reqres.hasHandler("default:region")).toBe(true);
    });
    return it("must return App main region as default region", function() {
      return expect(App.request("default:region")).toBe(App.rightRegion);
    });
  });
});
