// Generated by CoffeeScript 1.7.1
define(['app', 'apps/rooms/tariffs/tariffsapp'], function(App) {
  return describe("Rooms Tariff App", function() {
    return it("must have a Rooms Tariff app", function() {
      return should.exist(App.RoomsApp);
    });
  });
});
