// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    return App.module('SiteBuilderApp.Element.Row.Views', function(Views, App, Backbone, Marionette, $, _) {
      var _ref;
      return Views.RowView = (function(_super) {
        __extends(RowView, _super);

        function RowView() {
          _ref = RowView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        RowView.prototype.className = 'row';

        RowView.prototype.template = '<div class="col-md-6 column empty-column"></div><div class="col-md-6 column empty-column"></div>';

        RowView.prototype.onRender = function() {
          return this.$el.find('.column').sortable({
            revert: 'invalid',
            items: '> .element-wrapper',
            connectWith: '.droppable-column,.column',
            start: function(e, ui) {
              return ui.placeholder.height(ui.item.height());
            },
            helper: 'clone',
            opacity: .65,
            remove: function(evt, ui) {
              if ($(evt.target).children().length === 0) {
                return $(evt.target).addClass('empty-column');
              }
            },
            receive: function(e, ui) {
              return $(e.target).removeClass('empty-column');
            }
          });
        };

        return RowView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
