// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/builder/site-builder/settings/views'], function(App, AppController) {
    App.module('SiteBuilderApp.Settings', function(Settings, App, Backbone, Marionette, $, _) {
      var _ref;
      return Settings.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(opt) {
          var elementBoxModel, model, view, x, y,
            _this = this;
          if (opt == null) {
            opt = {};
          }
          model = opt.model, x = opt.x, y = opt.y;
          elementBoxModel = App.request("get:collection:model", 'elementbox', model.get('element'));
          view = new Settings.Views.SettingView({
            model: elementBoxModel,
            viewModel: model
          });
          this.listenTo(view, 'render', function() {
            _this.region.$el.css('top', x);
            return _this.region.$el.css('left', y);
          });
          return this.show(view);
        };

        return Controller;

      })(AppController);
    });
    return App.SiteBuilderApp.Settings.Controller;
  });

}).call(this);
