// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'tpl!apps/builder/site-builder/settings/templates/settings'], function(App, settingsTpl) {
    App.module('SiteBuilderApp.Settings.Views', function(Views, App, Backbone, Marionette, $, _) {
      var _ref;
      return Views.SettingView = (function(_super) {
        __extends(SettingView, _super);

        function SettingView() {
          _ref = SettingView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        SettingView.prototype.template = settingsTpl;

        SettingView.prototype.className = 'modal-content settings-box';

        SettingView.prototype.events = {
          'click .close-settings': function() {
            return App.settingsRegion.close();
          }
        };

        return SettingView;

      })(Marionette.ItemView);
    });
    return App.SiteBuilderApp.Settings.Views;
  });

}).call(this);
