// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'tpl!apps/site-profile/edit/templates/mainview', 'tpl!apps/site-profile/edit/templates/siteprofile'], function(App, mainviewTpl, siteprofileTpl) {
    App.module('SiteProfileApp.Edit.View', function(View, App, Backbone, Marionette, $, _) {
      var _ref, _ref1;
      View.SiteProfile = (function(_super) {
        __extends(SiteProfile, _super);

        function SiteProfile() {
          _ref = SiteProfile.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        SiteProfile.prototype.template = siteprofileTpl;

        SiteProfile.prototype.onRender = function() {
          return console.log(this.model);
        };

        SiteProfile.prototype.events = {
          'click .save-site-profile': function() {
            return this.triggers("save:site:profile");
          }
        };

        return SiteProfile;

      })(Marionette.ItemView);
      return View.MainView = (function(_super) {
        __extends(MainView, _super);

        function MainView() {
          _ref1 = MainView.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        MainView.prototype.template = mainviewTpl;

        return MainView;

      })(Marionette.ItemView);
    });
    return App.SiteProfileApp.Edit.View;
  });

}).call(this);
