// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/builder/header/show/views'], function(App, AppController) {
    App.module('HeaderApp.Show', function(Show, App, Backbone, Marionette, $, _) {
      var _ref;
      return Show.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(opt) {
          var view;
          if (opt == null) {
            opt = {};
          }
          view = new Show.View.MainView;
          return this.show(view);
        };

        return Controller;

      })(AppController);
    });
    return App.HeaderApp.Show.Controller;
  });

}).call(this);
