// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'apps/builder/site-builder/elements/menu/views'], function(App) {
    return App.module('SiteBuilderApp.Element.Menu', function(Menu, App, Backbone, Marionette, $, _) {
      var _ref;
      return Menu.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(options) {
          if (options == null) {
            options = {};
          }
          return Controller.__super__.initialize.call(this, options);
        };

        Controller.prototype._getMenuView = function(templates, menu) {
          return new Menu.Views.MenuView({
            collection: menu.get('menu_items'),
            templates: templates
          });
        };

        Controller.prototype.fetchNewStyle = function() {
          return console.log("fetch new style");
        };

        Controller.prototype.setupViews = function() {
          var menu, menuView, model, _ref1,
            _this = this;
          model = this.view.model;
          this.listenTo(model, 'change:style', this.fetchNewStyle);
          menu = App.request("create:menu:model", this.view.model.get('menu'));
          menuView = this._getMenuView((_ref1 = this.view.model.get('templates')) != null ? _ref1 : {}, menu);
          this.listenTo(menuView, "show:menu:manager", function(menuModel) {
            var menuId;
            menuId = menuModel.get('id');
            return App.navigate("menu-manager", {
              trigger: true
            });
          });
          menu.get('menu_items').each(function(model, index) {
            return _this.listenTo(model, 'change:order', menuView.render);
          });
          return this.addElementMarkup(menuView);
        };

        return Controller;

      })(App.SiteBuilderApp.Element.Controller);
    });
  });

}).call(this);
