// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    App.module('SiteBuilderApp.Element.Menu.Views', function(Views, App, Backbone, Marionette, $, _) {
      var _ref, _ref1, _ref2;
      Views.MenuItemView = (function(_super) {
        __extends(MenuItemView, _super);

        function MenuItemView() {
          this.template = __bind(this.template, this);
          _ref = MenuItemView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        MenuItemView.prototype.tagName = 'li';

        MenuItemView.prototype.template = function() {
          return this.options.template;
        };

        return MenuItemView;

      })(Marionette.ItemView);
      Views.SubMenuView = (function(_super) {
        __extends(SubMenuView, _super);

        function SubMenuView() {
          _ref1 = SubMenuView.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        SubMenuView.prototype.itemView = Views.MenuItemView;

        SubMenuView.prototype.itemViewContainer = 'ul.submenu';

        return SubMenuView;

      })(Marionette.CompositeView);
      return Views.MenuView = (function(_super) {
        __extends(MenuView, _super);

        function MenuView() {
          this.template = __bind(this.template, this);
          this.buildItemView = __bind(this.buildItemView, this);
          _ref2 = MenuView.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        MenuView.prototype.itemView = Views.MenuItemView;

        MenuView.prototype.buildItemView = function(item, ItemViewType, itemViewOptions) {
          var options;
          if (itemViewOptions == null) {
            itemViewOptions = {};
          }
          itemViewOptions.template = this.options.templates.menuItemTpl;
          options = _.extend({
            model: item
          }, itemViewOptions);
          return new ItemViewType(options);
        };

        MenuView.prototype.itemViewContainer = 'ul.menu';

        MenuView.prototype.template = function() {
          return this.options.templates.menuTpl;
        };

        MenuView.prototype.onBeforeRender = function() {
          return this.collection.sort();
        };

        return MenuView;

      })(Marionette.CompositeView);
    });
    return App.SiteBuilderApp.Element.Menu.Views;
  });

}).call(this);
