// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['builder/views/modals/Modal', 'tpl!builder/templates/modal/addpage.tpl', 'global'], function(Modal, template, global) {
    var AddPageModal, _ref;
    return AddPageModal = (function(_super) {
      __extends(AddPageModal, _super);

      function AddPageModal() {
        _ref = AddPageModal.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AddPageModal.prototype.id = 'add-page';

      AddPageModal.prototype.template = template;

      AddPageModal.prototype.className = 'modal';

      AddPageModal.prototype.initialize = function(options) {
        var html, markup;
        if (options == null) {
          options = {};
        }
        html = this.outerTemplate({
          title: 'Add New Page'
        });
        this.$el.html(html);
        $('body').append(this.$el);
        this.$el.modal();
        markup = this.template();
        return this.$el.find('.modal-content').append(markup);
      };

      return AddPageModal;

    })(Modal);
  });

}).call(this);
