// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['marionette', 'backbone', 'tpl!builder/templates/modal/singleroom.tpl', 'tpl!builder/templates/modal/rooms.tpl'], function(Marionette, Backbone, singleRoomTpl) {
    var RoomSingle, RoomsView, _ref, _ref1;
    RoomSingle = (function(_super) {
      __extends(RoomSingle, _super);

      function RoomSingle() {
        _ref = RoomSingle.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RoomSingle.prototype.template = singleRoomTpl;

      RoomSingle.prototype.events = {
        'click': 'roomSelected'
      };

      RoomSingle.prototype.roomSelected = function() {
        return getAppInstance().vent.trigger('room-selected', {
          room: this.model
        });
      };

      return RoomSingle;

    })(Marionette.ItemView);
    return RoomsView = (function(_super) {
      __extends(RoomsView, _super);

      function RoomsView() {
        _ref1 = RoomsView.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      RoomsView.prototype.itemView = RoomSingle;

      return RoomsView;

    })(Marionette.CollectionView);
  });

}).call(this);
