// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['builderelement', 'tpl!builder/templates/elements/BasicElement.tpl', 'global'], function(BuilderElement, template, global) {
    var ContactFormElement, _ref;
    return ContactFormElement = (function(_super) {
      __extends(ContactFormElement, _super);

      function ContactFormElement() {
        _ref = ContactFormElement.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ContactFormElement.prototype.className = 'aj-imp-elem-contact-form element ';

      ContactFormElement.prototype.template = template;

      ContactFormElement.prototype.elementType = 'ContactFormElement';

      ContactFormElement.prototype.events = {
        'mouseenter': 'elementMouseEnter',
        'mouseleave': 'elementMouseLeave',
        'click > .aj-imp-delete-btn': 'destroyElement',
        'contextmenu': 'showContextMenu'
      };

      ContactFormElement.prototype.initialize = function(options) {
        if (options == null) {
          options = {};
        }
        if (_.isUndefined(options.config)) {
          this.id = this.type() + '-' + global.generateRandomId();
          this.$el.attr('id', this.id);
        } else {
          this.setProperties(options.config);
        }
        this.generateMarkup({
          icon: '',
          name: 'Contact Form Element'
        });
        this.setContextMenu();
      };

      return ContactFormElement;

    })(BuilderElement);
  });

}).call(this);
