define ['polyglot', 'underscore'], (Polyglot, _ ) ->

    _.polyglot = new Polyglot
                phrases :
                    "My Dashboard" : "My Dashboard_N",
                    "Hi! Good to see you here. Lets get you started on Impruw." : "Hi! Good to see you here. Lets get you started on Impruw._N",
                    "Edit Site" : "Edit Site_N",
                    "Your website is ready:" : "Your website is ready:_N",
                    "My Site Profile" : "My Site Profile_N",
                    "Filling your Website profile is an essential step. Let us explain why?" : "Filling your Website profile is an essential step. Let us explain why?_N",
                    "It lets you add your" : "It lets you add your_N",
                    "Business details such as your logo, address etc" : "Business details such as your logo, address etc_N",
                    "Add your facebook/ twitter page urls." : "Add your facebook/ twitter page urls._N",
                    "Select the people that are allowed to edit your website" : "Select the people that are allowed to edit your website_N",
                    "We know how tedious it is to keep filling the same content over and over again every time you decide to change the design of your website so we like making things simpler. Fill in your website details once and that's it, your job is done.": "We know how tedious it is to keep filling the same content over and over again every time you decide to change the design of your website so we like making things simpler. Fill in your website details once and that's it, your job is done._N",
                    "Click here to update your website profile" : "Click here to update your website profile_N",
                    "Site Builder" : "Site Builder_N",
                    "Drag, drop and create a site in less than 30 minutes." : "Drag, drop and create a site in less than 30 minutes.",
                    "Our site builder makes it fast and easy to create a professional website in under 30 minutes. Our drag and drop editor allows you to add your content anywhere you want on the site. Simply add rows and drag - drop text or forms or images in the row." : "Our site builder makes it fast and easy to create a professional website in under 30 minutes. Our drag and drop editor allows you to add your content anywhere you want on the site. Simply add rows and drag - drop text or forms or images in the row._N",
                    "Customize your site with additional functionality like social media, contact forms and more." : "Customize your site with additional functionality like social media, contact forms and more._N",
                    "Click here to edit your website" : "Click here to edit your website_N",
                    "Rooms" : "Rooms_N",
                    "Add your room types, tariff and packages - at one place" : "Add your room types, tariff and packages - at one place_N",
                    "Impruw has been specifically designed to suit your business needs and therefore you can" : "Impruw has been specifically designed to suit your business needs and therefore you can_N",
                    "Add tariff according to your chosen date range" : "Add tariff according to your chosen date range_N",
                    "Add facilities and add ons to your room" : "Add facilities and add ons to your room_N",
                    "Create room types of your choice" : "Create room types of your choice_N",
                    "We want to make sure that you are able to create a business website that is completely yours - with your chosen room types to adding your unique business policies." : "We want to make sure that you are able to create a business website that is completely yours - with your chosen room types to adding your unique business policies._N",
                    "Click here to add rooms" : "Click here to add rooms_N",
                    "User Profile" : "User Profile_N",
                    "Complete your User Profile" : "Complete your User Profile_N",
                    "It's always nice to put a face to a name, so upload your profile picture." : "It's always nice to put a face to a name, so upload your profile picture._N",
                    "You can also change your password or your preferred language here." : "You can also change your password or your preferred language here._N",
                    "Click here to complete your user profile" : "Click here to complete your user profile_N",
