// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller'], function(App, AppController) {
    var FormController, _ref;
    return FormController = (function(_super) {
      __extends(FormController, _super);

      function FormController() {
        _ref = FormController.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FormController.prototype.initialize = function() {};

      return FormController;

    })(AppController);
  });

}).call(this);
