// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['dashboard-app', 'apps/leftnav/show/controller'], function(app, ShowController) {
    return app.module('LeftNav', function(LeftNav, App, Backbone, Marionette, $, _) {
      var API, _ref;
      this.startWithParent = false;
      LeftNav.Router = (function(_super) {
        __extends(Router, _super);

        function Router() {
          _ref = Router.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Router.prototype.appRoutes = {
          'leftNav': 'show'
        };

        return Router;

      })(Marionette.AppRouter);
      API = {
        show: new ShowController
      };
      return LeftNav.on({
        'start': function() {
          _.logAppMsg("LeftNav Module started...");
          return new Router({
            controller: API
          });
        }
      });
    });
  });

}).call(this);
