// Generated by CoffeeScript 1.6.3
(function() {
  define(['apps/builder/site-builder/elements/menu/controller', 'apps/builder/site-builder/elements/row/controller', 'apps/builder/site-builder/elements/logo/controller', 'apps/builder/site-builder/elements/text/controller', 'apps/builder/site-builder/elements/title/controller', 'apps/builder/site-builder/elements/image/controller'], function() {});

}).call(this);
