// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/media-manager/show/views'], function(App, AppController) {
    return App.module("MediaManager.Show", function(Show, App) {
      var _ref;
      return Show.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function() {
          this.layout = this._getLayout();
          this.show(this.layout);
          App.MediaManager.Upload.start({
            region: this.layout.uploadRegion
          });
          App.MediaManager.AllMedia.start({
            region: this.layout.allMediaRegion
          });
          return App.getRegion('elementsBoxRegion').hide();
        };

        Controller.prototype.onClose = function() {
          App.MediaManager.Upload.stop();
          App.navigate('');
          return App.getRegion('elementsBoxRegion').unhide();
        };

        Controller.prototype._getLayout = function(mediaCollection) {
          return new Show.Views.OuterLayout({
            collection: mediaCollection
          });
        };

        return Controller;

      })(AppController);
    });
  });

}).call(this);
