// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'text!apps/media-manager/show/templates/outer.html'], function(App, outerTpl) {
    return App.module('MediaManager.Show.Views', function(Views, App) {
      var _ref;
      return Views.OuterLayout = (function(_super) {
        __extends(OuterLayout, _super);

        function OuterLayout() {
          _ref = OuterLayout.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        OuterLayout.prototype.template = outerTpl;

        OuterLayout.prototype.regions = {
          uploadRegion: '#upload-region',
          allMediaRegion: '#all-media-region'
        };

        OuterLayout.prototype.dialogOptions = {
          modal_title: 'Media Manager'
        };

        return OuterLayout;

      })(Marionette.Layout);
    });
  });

}).call(this);
