// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/builder/elementsbox/show/views'], function(App, AppController) {
    App.module('ElementsBoxApp.Show', function(Show, App, Backbone, Marionette, $, _) {
      var _ref;
      return Show.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(opt) {
          var elements, view;
          if (opt == null) {
            opt = {};
          }
          elements = App.request("get:elementbox:elements");
          view = new Show.View.MainView({
            collection: elements
          });
          return this.show(view, {
            loading: true
          });
        };

        return Controller;

      })(AppController);
    });
    return App.ElementsBoxApp.Show.Controller;
  });

}).call(this);
