// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'tpl!apps/builder/elementsbox/show/templates/main'], function(App, mainviewTpl) {
    App.module('ElementsBoxApp.Show.View', function(View, App, Backbone, Marionette, $, _) {
      var _ref;
      return View.MainView = (function(_super) {
        __extends(MainView, _super);

        function MainView() {
          _ref = MainView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        MainView.prototype.template = mainviewTpl;

        MainView.prototype.className = 'aj-imp-drag-menu';

        MainView.prototype.id = 'controls-drag';

        return MainView;

      })(Marionette.CompositeView);
    });
    return App.ElementsBoxApp.Show.View;
  });

}).call(this);
