// Generated by CoffeeScript 1.6.3
(function() {
  define(["backbone"], function(Backbone) {
    var _sync;
    _sync = Backbone.sync;
    Backbone.sync = function(method, entity, options) {
      var sync;
      if (options == null) {
        options = {};
      }
      sync = _sync(method, entity, options);
      if (!entity._fetch && method === "read") {
        entity._fetch = sync;
        console.log("fetch sync");
      }
      return sync;
    };
  });

}).call(this);
