// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'underscore', 'polyglot'], function($, _, Polyglot) {
    var adjustPageDim;
    adjustPageDim = _.debounce(function() {
      var height, minHeight;
      height = $(window).height();
      minHeight = height - 40;
      $('.aj-upper-content').css('min-height', minHeight);
      return $('.aj-upper-content').children().css('min-height', minHeight);
    }, 30);
    $(document).ready(function() {
      return adjustPageDim();
    });
    $(window).resize(adjustPageDim);
    window.pt = new Polyglot({
      phrases: {}
    });
    return window.__ = function(key, opt) {
      if (opt == null) {
        opt = {};
      }
      return pt.t(key, opt);
    };
  });

}).call(this);
