// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  define(['underscore'], function(_) {
    _.templateSettings = {
      evaluate: /\{\[([\s\S]+?)\]\}/g,
      interpolate: /\{\{(.+?)\}\}/g
    };
    return _.mixin({
      logAppMsg: function() {
        var msg;
        msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return _.each(arguments, function(l, index) {
          return console.log(l);
        });
      },
      logAppErr: function() {
        var msg;
        msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return _.each(arguments, function(l, index) {
          return console.log(l);
        });
      }
    });
  });

}).call(this);
