// Generated by CoffeeScript 1.6.3
(function() {
  define(['marionette'], function(Marionette) {
    var App;
    App = new Marionette.Application;
    App.addRegions({
      leftRegion: '#aj-imp-left',
      rightRegion: '#aj-imp-right',
      footerRegion: '#footer-section'
    });
    App.rootRoute = "dashboard";
    App.addInitializer(function() {
      return App.module('LeftNav').start();
    });
    App.on('start', function() {
      return _.logAppMsg("Application Started....");
    });
    App.addInitializer(function(options) {
      return App.LeftNav.start();
    });
    App.reqres.setHandler("default:region", function() {
      return App.rightRegion;
    });
    App.commands.setHandler("register:instance", function(instance, id) {
      return App.register(instance, id);
    });
    App.commands.setHandler("unregister:instance", function(instance, id) {
      return App.unregister(instance, id);
    });
    App.on("initialize:after", function(options) {
      App.startHistory();
      if (!this.getCurrentRoute()) {
        return App.navigate(this.rootRoute, {
          trigger: true
        });
      }
    });
    return App;
  });

}).call(this);
