// Generated by CoffeeScript 1.7.1
(function() {
  define(['app', 'controllers/base-controller', 'apps/media/upload/controller', 'apps/media/grid/controller', 'apps/media/selected/controller', 'apps/media/edit-media/controller'], function(App, AppController, outerTpl) {
    return App.module('Media', function(Media, App, Backbone, Marionette, $, _) {});
  });

}).call(this);
