// Generated by CoffeeScript 1.6.3
(function() {
  define(['dashboard-app'], function(app) {
    return app.module('LeftNav.Show', function(Show, App, Backbone, Marionette, $, _) {});
  });

}).call(this);
