// Generated by CoffeeScript 1.6.3
(function() {
  define(['dashboard-app'], function(App) {
    return App.module('LeftNav.Show', function(Show, App, Backbone, Marionette, $, _) {
      this.startWithParent = false;
      return Show.Controller = {
        showLeftNav: function() {}
      };
    });
  });

}).call(this);
