// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['dashboard-app', 'tpl!apps/leftnav/show/templates/leftNav.tpl', 'tpl!apps/leftnav/show/templates/menuitem.tpl'], function(App, leftNavTpl, menuitemTpl) {
    App.module('LeftNav.Show.View', function(View, App, Backbone, Marionette, $, _) {
      var _ref, _ref1;
      View.LeftNav = (function(_super) {
        __extends(LeftNav, _super);

        function LeftNav() {
          _ref = LeftNav.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        LeftNav.prototype.template = leftNavTpl;

        LeftNav.prototype.itemViewContainer = '#aj-imp-dash-menu';

        return LeftNav;

      })(Marionette.CompositeView);
      return View.MenuItem = (function(_super) {
        __extends(MenuItem, _super);

        function MenuItem() {
          _ref1 = MenuItem.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        MenuItem.prototype.template = menuitemTpl;

        return MenuItem;

      })(Marionette.ItemView);
    });
    return App.LeftNav.Show.View;
  });

}).call(this);
