// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/builder/site-builder/show/views'], function(App, AppController) {
    App.module('SiteBuilderApp.Show', function(Show, App, Backbone, Marionette, $, _) {
      var _ref, _ref1;
      Show.BuilderController = (function(_super) {
        __extends(BuilderController, _super);

        function BuilderController() {
          _ref = BuilderController.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        BuilderController.prototype.initialize = function(opt) {
          var elements, pageId,
            _this = this;
          if (opt == null) {
            opt = {};
          }
          this.region = App.getRegion('builderRegion');
          pageId = 5;
          elements = App.request("get:page:json", pageId);
          this.view = new Show.View.Builder({
            model: elements
          });
          this.listenTo(this.view, "element:dropped", function(container, type) {
            return App.vent.trigger("element:dropped", container, type);
          });
          this.listenTo(this.view, "dependencies:fetched", function() {
            return _.delay(function() {
              return _this.startFillingElements();
            }, 2000);
          });
          return this.show(this.view, {
            loading: true
          });
        };

        BuilderController.prototype._getContainer = function(section) {
          switch (section) {
            case 'header':
              return $('#site-header-region');
            case 'page':
              return $('#site-page-content-region');
            case 'footer':
              return $('#site-footer-region');
          }
        };

        BuilderController.prototype.startFillingElements = function() {
          var json,
            _this = this;
          json = this.view.model.get('json');
          return _.each(json, function(section, key) {
            var container;
            container = _this._getContainer(key);
            return _.each(section, function(element, index) {
              return App.vent.trigger("element:dropped", container, element.element, element);
            });
          });
        };

        return BuilderController;

      })(AppController);
      return Show.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref1 = Controller.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        Controller.prototype.initialize = function(opt) {
          var view;
          if (opt == null) {
            opt = {};
          }
          this.region = App.getRegion('builderWrapper');
          view = new Show.View.MainView;
          this.listenTo(view, 'render', function(view) {
            return _.delay(function() {
              App.addRegions({
                builderRegion: '#aj-imp-builder-drag-drop'
              });
              return new Show.BuilderController();
            }, 400);
          });
          return this.show(view);
        };

        return Controller;

      })(AppController);
    });
    return App.SiteBuilderApp.Show.Controller;
  });

}).call(this);
