// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'text!apps/builder/site-builder/show/templates/maintemplate.html', 'text!apps/builder/site-builder/show/templates/builder.html'], function(App, mainviewTpl, builderTpl) {
    App.module('SiteBuilderApp.Show.View', function(View, App, Backbone, Marionette, $, _) {
      var _ref, _ref1;
      View.MainView = (function(_super) {
        __extends(MainView, _super);

        function MainView() {
          _ref = MainView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        MainView.prototype.template = mainviewTpl;

        MainView.prototype.className = 'aj-imp-builder-area';

        MainView.prototype.events = {
          'click .auto-save': function(evt) {
            evt.preventDefault();
            return App.commands.execute("auto:save");
          }
        };

        return MainView;

      })(Marionette.Layout);
      return View.Builder = (function(_super) {
        __extends(Builder, _super);

        function Builder() {
          _ref1 = Builder.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        Builder.prototype.template = builderTpl;

        Builder.prototype.onShow = function() {
          var _this = this;
          return this.$el.find('.droppable-column').sortable({
            revert: 'invalid',
            items: '> .element-wrapper',
            connectWith: '.droppable-column,.column',
            start: function(e, ui) {
              return ui.placeholder.height(ui.item.height());
            },
            handle: '.aj-imp-drag-handle',
            helper: 'clone',
            opacity: .65,
            receive: function(evt, ui) {
              var type;
              if (ui.item.prop("tagName") === 'LI') {
                type = ui.item.attr('data-element');
                return _this.trigger("element:dropped", $(evt.target), type);
              }
            }
          });
        };

        return Builder;

      })(Marionette.ItemView);
    });
    return App.SiteBuilderApp.Show.View;
  });

}).call(this);
