define [
		'entities/base-entities'
		'entities/offlinestore'
		'entities/analytics'
		'entities/rooms'
		'entities/facilities'
		'entities/site'
		'entities/media'
		'entities/slider'
		'entities/plans'
		'entities/tariff'
		'entities/user'
		'entities/daterange'
		'entities/booking'
		],->
