// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'apps/builder/site-builder/elements/title/views', 'apps/builder/site-builder/elements/title/settings/controller'], function(App) {
    return App.module('SiteBuilderApp.Element.Title', function(Title, App, Backbone, Marionette, $, _) {
      var _ref;
      return Title.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          this.renderElement = __bind(this.renderElement, this);
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(options) {
          _.defaults(options.modelData, {
            element: 'Title',
            content: 'Click here to enter title'
          });
          return Controller.__super__.initialize.call(this, options);
        };

        Controller.prototype.bindEvents = function() {
          return Controller.__super__.bindEvents.call(this);
        };

        Controller.prototype._getTitleView = function(model) {
          return new Title.Views.TitleView({
            model: model
          });
        };

        Controller.prototype.renderElement = function() {
          var view,
            _this = this;
          this.removeSpinner();
          view = this._getTitleView(this.layout.model);
          this.listenTo(view, "title:element:blur", function(html) {
            _this.layout.model.set('content', "" + html);
            if (_this.layout.model.hasChanged()) {
              return _this.layout.model.save();
            }
          });
          return this.layout.elementRegion.show(view);
        };

        return Controller;

      })(App.SiteBuilderApp.Element.Controller);
    });
  });

}).call(this);
