// Generated by CoffeeScript 1.7.1
(function() {
  describe("new Spec added", function() {
    it("must save time", function() {
      return expect("Save time").toBe("Save time");
    });
    return it("must have window object defined", function() {
      return expect("#href").toBe('#href');
    });
  });

}).call(this);

//# sourceMappingURL=spec.builder.map
