// Generated by CoffeeScript 1.7.1
var js;

require.config({
  urlArgs: "ver=" + (Math.random()),
  baseUrl: '../js/',
  paths: {
    jquery: 'plugins/jquery',
    jqueryui: 'plugins/jquery.ui',
    underscore: 'plugins/underscore',
    backbone: 'plugins/backbone',
    marionette: 'plugins/backbone.marionette',
    tpl: 'plugins/tpl',
    text: 'plugins/text',
    spin: 'plugins/spin',
    jqueryspin: 'plugins/jquery.spin',
    bootstrap: 'plugins/bootstrap',
    bootstrapselect: 'plugins/bootstrapselect',
    underscorestring: 'plugins/underscore.string',
    mustache: 'plugins/Mustache',
    plupload: 'plugins/plupload.full',
    d3: 'plugins/d3.v3',
    nvd3: 'plugins/nv.d3',
    radio: 'plugins/flatui-radio',
    checkbox: 'plugins/flatui-checkbox',
    backboneform: 'plugins/backbone.form',
    backbonesyphon: 'plugins/backbone.syphon',
    backboneassociations: 'plugins/backbone.associations',
    jqueryvalidate: 'plugins/jquery.validate',
    polyglot: 'plugins/polyglot',
    jpanelmenu: 'plugins/jquery.jpanelmenu.min',
    scrollsections: 'plugins/ajency.scrolldots',
    minicolors: 'plugins/jquery.minicolors.min',
    isotope: 'plugins/isotope',
    moment: 'plugins/moment',
    chart: 'plugins/chart',
    app: 'dashboard-app',
    bootstrapswitch: 'plugins/bootstrap-switch',
    entitiesloader: 'entities/dashboard-entities-loader'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    jquery: ['underscore'],
    jqueryui: ['jquery'],
    backbone: {
      deps: ['jquery', 'underscore'],
      exports: 'Backbone'
    },
    marionette: {
      deps: ['backbone'],
      exports: 'Marionette'
    },
    polyglot: {
      exports: 'Polyglot'
    },
    plupload: {
      deps: ['jquery'],
      exports: 'plupload'
    },
    nvd3: {
      deps: ['d3'],
      exports: 'nv'
    },
    jqueryvalidate: ['jquery'],
    scrollsections: ['jquery'],
    jpanelmenu: ['jquery'],
    minicolors: ['jquery'],
    isotope: ['jquery'],
    underscorestring: ['underscore'],
    backboneform: ['backbone'],
    backbonesyphon: ['backbone'],
    backboneassociations: ['backbone'],
    jqueryspin: ['spin'],
    bootstrap: ['jquery'],
    radio: ['bootstrap'],
    checkbox: ['bootstrap'],
    bootstrapselect: ['bootstrap'],
    bootstrapswitch: ['bootstrap'],
    app: ['plugins/plugin-loader', 'configs/config-loader']
  }
});

js = ['plugins/plugin-loader', 'configs/config-loader', 'app'];

require(js, function(plugins, configs, App) {
  var specs;
  specs = [];
  specs.push('../tests/spec/notification.spec');
  specs.push('../tests/spec/app.spec');
  return require(specs, function() {
    return jasmine.getEnv().execute();
  });
});
