// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var RoomCollection, RoomModel, _ref, _ref1;
    RoomModel = (function(_super) {
      __extends(RoomModel, _super);

      function RoomModel() {
        _ref = RoomModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RoomModel.prototype.idAttribute = 'ID';

      RoomModel.prototype.defaults = {
        post_title: '',
        post_content: '',
        image: ''
      };

      return RoomModel;

    })(Backbone.Model);
    RoomCollection = (function(_super) {
      __extends(RoomCollection, _super);

      function RoomCollection() {
        _ref1 = RoomCollection.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      RoomCollection.prototype.url = AJAXURL + '?action=get-all-rooms';

      RoomCollection.prototype.parse = function(resp) {
        if (resp.code === 'OK') {
          return resp.data;
        }
      };

      return RoomCollection;

    })(Backbone.Collection);
    return {
      RoomModel: RoomModel,
      RoomCollection: RoomCollection
    };
  });

}).call(this);
