// Generated by CoffeeScript 1.6.3
(function() {
  define(['apps/dashboard/app', 'apps/leftnav/app', 'apps/rooms/app', 'apps/site-profile/app', 'apps/my-profile/app'], function() {});

}).call(this);
