// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'text!apps/media-manager/upload/templates/upload.html'], function(App, uploadTpl) {
    return App.module('MediaManager.Upload.Views', function(Views, App) {
      var _ref;
      return Views.UploadView = (function(_super) {
        __extends(UploadView, _super);

        function UploadView() {
          _ref = UploadView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        UploadView.prototype.template = uploadTpl;

        return UploadView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
