// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/builder-base-controller', 'apps/builder/site-builder/element/views'], function(App, AppController) {
    App.module('SiteBuilderApp.Element', function(Element, App, Backbone, Marionette, $, _) {
      var _ref;
      return Element.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(opt) {
          var container, evt, options, type, ui, view;
          if (opt == null) {
            opt = {};
          }
          evt = opt.evt, ui = opt.ui;
          container = $(evt.target);
          type = ui.helper.attr('data-element');
          if ($(evt.target).hasClass('empty-column')) {
            $(evt.target).removeClass('empty-column');
          }
          options = {
            elementType: type,
            draggable: true
          };
          this.element = App.request("create:new:element", options);
          view = this._getView(this.element);
          this.listenTo(view, "show:setting:popup", this.showSettingPopup);
          this.listenTo(view, "element:dropped", function(evt, ui) {
            return App.vent.trigger("element:dropped", evt, ui);
          });
          return this.add(view, container);
        };

        Controller.prototype._getView = function(element) {
          return new Element.Views.ElementView({
            model: element
          });
        };

        Controller.prototype.showSettingPopup = function(x, y) {
          return App.vent.trigger("show:settings:popup", this.element, x, y);
        };

        return Controller;

      })(AppController);
    });
    return App.SiteBuilderApp.Element.Controller;
  });

}).call(this);
