// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'apps/builder/site-builder/elements/menu/settings/settings.html'], function(App, settingTpl) {
    return App.module('SiteBuilderApp.Element.Menu.Settings.Views', function(Views, App, Backbone, Marionette, $, _) {
      var SettingView, _ref;
      return SettingView = (function(_super) {
        __extends(SettingView, _super);

        function SettingView() {
          _ref = SettingView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        SettingView.prototype.template = settingsTpl;

        return SettingView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
