##
## Load any JS plugins if required
##
define [
   'underscore'
   'jquery'
   'jqueryui'
   'backbone'
   'marionette'
   'backbonesyphon'
   'mustache'
   'underscorestring'
   'jqueryvalidate'
   'bootstrap'
   'bootbox'
   'radio'
   'checkbox'
   'json2'
   'imageareaselect'
   'imageedit'
   'svgpainter'
   'cookie'
   'plupload'
   'text'
   'jqueryspin'
   'polyglot'
   'bootstrapselect'
   'imgLiquid'
   'nestedsortable'
   'themepunch'
   'revslider'
   'isotope'
   'moment'
   'minicolors'
   'drilldown'
   #'flippant'
], ->