##
## Load any JS plugins if required
##
define [
		'underscore'
		'jquery'
		'jqueryui'
		'backbone'
		'marionette'
		'backbonesyphon'
		'mustache'
		'backboneassociations'
		'underscorestring'
		'jqueryvalidate'
		'bootstrap'
		'radio'
		'checkbox'
		'cookie'
		'holder'
		'plupload'
		'text'
		'jqueryspin'
		'bootstrapselect'
		'ckeditor'
		'nestedsortable'
		'themepunch'
		'revslider'
		'isotope'
		],->