##
## Load any JS plugins if required
##
define [
   'underscore'
   'jquery'
   'jqueryui'
   'backbone'
   'backbonesyphon'
   'jqueryvalidate'
   'marionette'
   'bootstrap'
   'json2'
   'imageareaselect'
   'imageedit'
   'svgpainter'
   'radio'
   'checkbox'
   'moment'
   'text'
   'jqueryspin'
   'underscorestring'
   'mustache'
   'bootstrapselect'
   'isotope'
   'lightbox'
   'jpanelmenu'
   'minicolors'
   'polyglot'
   'additionalmethod'
   'timepicker'
], ->