// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'apps/media-manager/upload/controller', 'apps/media-manager/all-media/controller', 'apps/media-manager/show/controller'], function(App) {
    return App.module('MediaManager', function(MediaManager, App, Backbone, Marionette, $, _) {
      var API, _ref;
      MediaManager.Router = (function(_super) {
        __extends(Router, _super);

        function Router() {
          _ref = Router.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Router.prototype.appRoutes = {
          'media-manager': 'show'
        };

        return Router;

      })(Marionette.AppRouter);
      API = {
        show: function() {
          return new MediaManager.Show.Controller({
            region: App.dialogRegion
          });
        }
      };
      App.vent.on("show:media:manager", function() {
        return API.show();
      });
      return MediaManager.on("start", function() {
        return new MediaManager.Router({
          controller: API
        });
      });
    });
  });

}).call(this);
