// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'controllers/base-controller', 'apps/media-manager/edit-media/views'], function(App, AppController) {
    return App.module("MediaManager.EditMedia", function(EditMedia, App) {
      var _ref;
      EditMedia.Controller = (function(_super) {
        __extends(Controller, _super);

        function Controller() {
          _ref = Controller.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Controller.prototype.initialize = function(opt) {
          var model, view;
          if (opt == null) {
            opt = {};
          }
          model = opt.model;
          view = this._getView(model);
          return this.show(view);
        };

        Controller.prototype._getView = function(mediaModel) {
          return new EditMedia.Views.EditMediaView({
            model: mediaModel
          });
        };

        return Controller;

      })(AppController);
      return App.vent.on("media:element:clicked", function(model, region) {
        return new EditMedia.Controller({
          model: model,
          region: region
        });
      });
    });
  });

}).call(this);
