// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    return App.module('SiteBuilderApp.Element.Social.Views', function(Views, App, Backbone, Marionette, $, _) {
      var _ref;
      return Views.SocialView = (function(_super) {
        __extends(SocialView, _super);

        function SocialView() {
          _ref = SocialView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        SocialView.prototype.className = 'social';

        return SocialView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
