// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app'], function(App) {
    return App.module('SiteBuilderApp.Element.Social.Views', function(Views, App, Backbone, Marionette, $, _) {
      var SocialItem, _ref, _ref1;
      SocialItem = (function(_super) {
        __extends(SocialItem, _super);

        function SocialItem() {
          _ref = SocialItem.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        SocialItem.prototype.tagName = 'li';

        SocialItem.prototype.template = '<a href="{{sociallink}}" target="_BLANK" class="icon-facebook"></a>';

        SocialItem.prototype.onRender = function() {
          return this.$el.addClass("social-" + (_.slugify(this.model.get('socialname'))));
        };

        return SocialItem;

      })(Marionette.ItemView);
      return Views.SocialView = (function(_super) {
        __extends(SocialView, _super);

        function SocialView() {
          _ref1 = SocialView.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        SocialView.prototype.tagName = 'ul';

        SocialView.prototype.className = 'social';

        SocialView.prototype.itemView = SocialItem;

        SocialView.prototype.onRender = function() {
          var className, style;
          style = Marionette.getOption(this, 'style');
          className = _.slugify(style);
          return this.$el.addClass(className);
        };

        return SocialView;

      })(Marionette.CollectionView);
    });
  });

}).call(this);
