// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['app', 'holder'], function(App, Holder) {
  return App.module('SiteBuilderApp.Element.RoomSummary.Views', function(Views, App, Backbone, Marionette, $, _) {
    var _ref;
    return Views.RoomSummaryView = (function(_super) {
      __extends(RoomSummaryView, _super);

      function RoomSummaryView() {
        _ref = RoomSummaryView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RoomSummaryView.prototype.className = 'roomsummary';

      RoomSummaryView.prototype.template = 'Room Summary template';

      return RoomSummaryView;

    })(Marionette.ItemView);
  });
});
