// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['builderelement', 'tpl!builder/templates/elements/BasicElement.tpl', 'global'], function(BuilderElement, template, global) {
    var RoomTariff, _ref;
    return RoomTariff = (function(_super) {
      __extends(RoomTariff, _super);

      function RoomTariff() {
        _ref = RoomTariff.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RoomTariff.prototype.className = 'aj-imp-elem-room-tariff element ';

      RoomTariff.prototype.template = template;

      RoomTariff.prototype.elementType = 'RoomTariff';

      RoomTariff.prototype.dataSource = 0;

      RoomTariff.prototype.events = {
        'mouseenter': 'elementMouseEnter',
        'mouseleave': 'elementMouseLeave',
        'click > .aj-imp-delete-btn': 'destroyElement',
        'contextmenu': 'showContextMenu',
        'click a': 'void'
      };

      RoomTariff.prototype.initialize = function(options) {
        if (options == null) {
          options = {};
        }
        if (_.isUndefined(options.config)) {
          this.id = this.type() + '-' + global.generateRandomId();
          this.$el.attr('id', this.id);
        } else {
          this.setProperties(options.config);
        }
        this.generateMarkup({
          icon: '',
          name: 'Room Tariff'
        });
        this.setContextMenu();
      };

      RoomTariff.prototype.hasExtraSettings = function() {
        var html, options;
        options = '';
        _.each(['all', 'min'], _.bind(function(ele, index) {
          var selected;
          if (this.dataSource === ele) {
            selected = 'selected="selected"';
          } else {
            selected = '';
          }
          options += "<option value='" + ele + "' " + selected + ">" + (_.capitalize(ele)) + "</option>";
        }, this));
        return html = "<div class='form-group'><select name='show'>					" + options + "					</select></div>";
      };

      RoomTariff.prototype.updateExtraProperties = function(evt) {
        var pcontent;
        if (evt == null) {
          evt = {};
        }
        pcontent = $(evt.target).closest('.popover');
        return this.dataSource = $(pcontent).find('select[name="show"]').val();
      };

      return RoomTariff;

    })(BuilderElement);
  });

}).call(this);
