// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'apps/menu-manager/show/controller'], function(App) {
    return App.module('MenuManager', function(MenuManager, App, Backbone, Marionette, $, _) {
      var API, _ref;
      MenuManager.Router = (function(_super) {
        __extends(Router, _super);

        function Router() {
          _ref = Router.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Router.prototype.appRoutes = {
          'menu-manager': 'show'
        };

        return Router;

      })(Marionette.AppRouter);
      API = {
        show: function() {
          return new MenuManager.Show.Controller({
            region: App.dialogRegion
          });
        }
      };
      return MenuManager.on({
        'start': function() {
          _.logAppMsg("MenuManager Module started...");
          return new MenuManager.Router({
            controller: API
          });
        }
      });
    });
  });

}).call(this);
