// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'apps/menu-manager/show/controller'], function(App) {
    return App.module('MenuManager', function(MenuManager, App, Backbone, Marionette, $, _) {
      var API;
      API = {
        show: function() {
          return new MenuManager.Show.Controller({
            region: App.dialogRegion
          });
        }
      };
      App.vent.on("show:menu:manager", function() {
        return API.show();
      });
      return MenuManager.on({
        'start': function() {
          return _.logAppMsg("MenuManager Module started...");
        }
      });
    });
  });

}).call(this);
