// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore', 'jquery', 'backbone', 'backboneform', 'backbonesyphon', 'backbonerelational', 'jqueryvalidate', 'marionette', 'bootstrap', 'radio', 'checkbox', 'tpl', 'jqueryspin', 'polyglot', 'bootstrapselect'], function() {});

}).call(this);
